feat: add build instructions to README
osdev-wiki/wiki pull request #27
Opened 2022-06-03 15:13 UTC by xy2iii

Add some simple instructions to build the wiki generator.

2022-06-03 16:13 UTC, pitust requested changes

2022-06-03 16:13 UTC, pitust commented on README.md
> +Thanks for contributing!
this is a little out of place

2022-06-03 16:13 UTC, pitust commented on README.md
> +This wiki is written in Haskell. You will need a [Stack](https://docs.haskellstack.org/en/stable/README/) installation to compile and run the main binary.
... need a Stack installation ... => ... need to have Stack installed ...

2022-06-03 16:13 UTC, pitust commented on README.md
> +The project also depends on some non-Haskell deps. To install these, you need a [Python](https://www.python.org/downloads/), [Ruby](https://www.ruby-lang.org/fr/documentation/installation/) and [Rust
... need a Python ... => ... need Python ...

less sure about this one: ... need ... => ... will need ...

2022-06-04 05:16 UTC, ArsenArsen commented
I'd suggest also mentioning `nix`, and providing instructions on how to use the binary cache (`s3://osdev-wiki-cache?scheme=https&endpoint=s3.us-west-000.backblazeb2.com`, but I might swap that out for s3 in the future, if I do so, I'll update the README, no need to worry) as this could significantly cut down on build time. It's also possible that I'll be including adoc, the plugins, pygments and stork in the cache as external deps to make the process further simpler.

Thank you for the writeup!

2022-06-05 11:52 UTC, xy2iii reviewed
ok

2022-06-05 12:04 UTC, xy2iii commented on README.md
> +Thanks for contributing!
removed

2022-06-10 15:13 UTC, ArsenArsen requested changes
Overall, quite good, thank you for the effort.

Please squash commits into a single `feat(misc): add instructions for the to README` or such when we're done here.

2022-06-10 15:13 UTC, ArsenArsen commented on README.md
> +The project has some non-Haskell dependencies. To install these, you will need [Python](https://www.python.org/downloads/), [Ruby](https://www.ruby-lang.org/fr/documentation/installation/) and [Rust]
One of these links is French.

I also feel like instructing the user on how to get runtimes is unnecessary. All of the other dependencies are distinct projects with their own dependencies, so it should be left up to them to instruct on obtaining them.

2022-06-10 15:13 UTC, ArsenArsen commented on README.md
> +[Install nix](https://nixos.org/download.html#download-nix). Please use the single-user installation as it's easier to set up.
Whether to use single user should be up to the user (same idea as before, dealing with dependencies is out of place for us to instruct, and could only serve to cause confusion).

2022-06-10 16:11 UTC, ArsenArsen approved these changes
lgtm, waiting on peer review as I am too sleepy to do proper grammar

2022-06-25 12:45 UTC, xy2iii commented
Friendly ping on this

2022-06-25 12:55 UTC, pitust approved these changes
Language is correct (i think...)

2022-10-06 19:25 UTC, closed without merging